global:
  scrape_interval: 15s  # How frequently Prometheus scrapes metrics

scrape_configs:
  - job_name: 'jenkins-pipeline'
    static_configs:
      - targets: ['http://192.168.56.10:8080/metrics']  # Replace with Jenkins URL exposing Prometheus metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Prometheus service in Docker network
